feat: support server redirects
molefrog/wouter pull request #491
Opened 2024-10-23 21:12 UTC by gbettencourt

Add the ability to redirect during SSR.  Currently wouter only supports redirect once the app hydrates and the components render client side.  Being able to redirect from the server is more efficient (only requires sending a status code back), resulting in better user experience.  The response can also be cached by the browser.

2024-12-10 18:55 UTC, radfahrer commented
@molefrog, we would greatly appreciate it if you could review this PR. We would very much like to migrate our application from `react-router` to `wouter` and this piece of missing functionality is holding us up.

2025-01-25 00:20 UTC, molefrog requested changes
Hey! I am so sorry for my long reply. I've added a few comments, could you take a look?

2025-01-25 00:20 UTC, molefrog commented on README.md
> +    <Router ssrPath={req.path} ssrSearch={req.search} ssrContext={ssrContext}>
How about a shorter name `ssrCtx`?

2025-01-25 00:20 UTC, molefrog commented on packages/wouter/src/index.js
> +  }
We already use optional chaining in the library, so it is safe to write:

```suggestion
  ssrContext?.redirectTo = to;
```

2025-01-25 00:20 UTC, molefrog commented on packages/wouter/src/index.js
> +  const { ssrContext } = useRouter();
There is an internal helper hook `useLocationFromRouter` that you can use combined with `useRouter()` to avoid extra context calls.

2025-01-27 22:31 UTC, gbettencourt commented on README.md
> +    <Router ssrPath={req.path} ssrSearch={req.search} ssrContext={ssrContext}>
Given the other props used in the above example (`ssrPath` and `ssrSearch`) IMO `Context` fits better then an abbreviation.  Not sure there's any benefit to being terse here.

2025-01-27 22:32 UTC, gbettencourt commented on packages/wouter/src/index.js
> +  }
This fails linting: "Parsing error: Optional chaining cannot appear in left-hand side".

2025-01-27 22:33 UTC, gbettencourt commented on packages/wouter/src/index.js
> +  const { ssrContext } = useRouter();
Not sure I understand this suggestion, there's no need to use location (the result of `useLocationFromRouter`) in this instance.

2025-01-27 22:35 UTC, gbettencourt commented on packages/wouter/src/index.js
> +  const { ssrContext } = useRouter();
oh never-mind, I see.  I can optimize the existing call to `useLocation` above since I have a router ref.  I pushed the changes.

2025-01-28 01:10 UTC, molefrog commented on packages/wouter/src/index.js
> +  }
My bad, optional chaining doesn't work with assignments.

2025-01-28 01:11 UTC, molefrog approved these changes

2025-01-28 01:11 UTC, merged

2025-01-28 01:15 UTC, molefrog commented
Released in v3.5.0
Thank you!