Feat: memory location search hook
molefrog/wouter pull request #497
Opened 2024-11-14 11:07 UTC by mitulagr2

Return `searchHook` from `memoryLocation`. This can be passed to `Router`.

fixes #447

2025-02-05 13:29 UTC, tillprochaska commented
Hi @mitulagr2, thanks for taking the time to fix this. I’m currently working on an app that makes heavy use of URL search parameters to encode/share UI state, so I’m quite interested in better testing support for the `useSearch` hook.

I’ve tested your changes and noticed a few issues:

* The location hook includes the search string in the returned value. The default browser location hook returns the path only.
* The search hook returns a single-valued array, whereas the browser location search hook returns a string.

I’ve tried to fix these issues here: https://github.com/tillprochaska/wouter/tree/memory-location-search-hook

@molefrog I’ve seen that this PR has been open for quite a while. Is there anything else I could help with to move this forward?

I saw that the recent release includes a new `useSearchParams` hook. It would probably be nice if the memory location implementation had support for that as well, but that could probably be added separately on top of these changes.

2025-02-10 17:22 UTC, molefrog commented
> I saw that the recent release includes a new `useSearchParams` hook. It would probably be nice if the memory location implementation had support for that as well, but that could probably be added separately on top of these changes.

`useSearchParams` uses `useSearch` internal so it should work automatically with any location hook.

2025-02-10 17:23 UTC, molefrog commented
Sadly, I started reviewing this PR a while a ago and I didn't press send.

2025-02-10 17:27 UTC, molefrog requested changes

2025-02-10 17:27 UTC, molefrog commented on packages/wouter/test/memory-location.test.ts
> +  // const { searchHook } = memoryLocation({ path: "/test-case", searchPath: "foo=bar" });
Probably some leftover

2025-02-10 17:27 UTC, molefrog commented on packages/wouter/test/memory-location.test.ts
> +
One test case that is missing is when `memoryLocation` accepts `searchPath` as a parameter.

2025-02-10 17:27 UTC, molefrog commented on packages/wouter/test/use-search.test.tsx
> +
Same here. Would be nice to test `searchPath` param as well.

2025-02-10 17:27 UTC, molefrog commented on packages/wouter/src/memory-location.js
> +  let currentSearch = currentPath.split("?")[1] || "";
Could this piece of code be simplified somehow?

2025-02-11 16:00 UTC, tillprochaska commented
@molefrog Thanks for the update!

@mitulagr2 In case this PR isn’t relevant to you anymore or you don’t have time, feel free to let me know and I’m happy to pick up the PR and apply the requested changes :)

2025-02-11 18:58 UTC, mitulagr2 commented
Thanks for the review! I'll push the changes by tomorrow

2025-02-12 13:18 UTC, mitulagr2 commented
@molefrog @tillprochaska Could you please let me know if there's anything else that needs to be changed?

Currently, the memory location hook does not throw any error if both, explicit search parameter and path with search query are used simultaneously

```
const { hook, searchHook } = memoryLocation({ path: '/foo?key=value' });
<Router hook={hook} searchHook={searchHook}>

// or more explicit
const { hook, searchHook } = memoryLocation({ path: '/foo', searchPath: 'key=value' });

// also valid
const { hook, searchHook } = memoryLocation({ path: '/foo?foo=bar', searchPath: 'key=value' });
```

2025-02-12 18:02 UTC, tillprochaska reviewed
Hi @mitulagr2, that’s great, thank you!

I think there are still two small issues where there memory location implementation would be different from the default browser location implementation (see comments below).

2025-02-12 18:02 UTC, tillprochaska commented on packages/wouter/src/memory-location.js
> +  let currentPath = initialPath;
The default browser location implementation returns only the path without the search query:

```js
// Current browser location: /foo?key=value
const location = useLocation() // returns just /foo
```

But the current implementation includes the search query:

```js
const { hook } = memoryLocation({ path: '/foo?key=value' });
const location = useLocation() // returns /foo?key=value
```

So you’d need to do something like this here and a little further down in `navigateImplementation`:

```
let currentPath = initialPath.split("?")[0];
```

2025-02-12 18:02 UTC, tillprochaska commented on packages/wouter/src/memory-location.js
> +  ];
The default browser location hook returns just the query string (instead of the single-value array returned here).

2025-02-12 18:32 UTC, mitulagr2 commented
Thank you for the detail! I've made said changes.

2025-02-12 19:09 UTC, molefrog approved these changes
LGTM!

2025-02-12 20:12 UTC, tillprochaska commented on packages/wouter/src/memory-location.js
>    const history = [currentPath];
Just one more thing to fix the initial entry in the history array, now that `currentPath` doesn’t include the query string anymore.

```suggestion
  const history = [initialPath];
```

Otherwise this wouldn’t work:

```js
const { history } = memoryLocation({ path: "/foo?key=value" });
// history[0] is `/foo`, but should be `/foo?key=value`
```

2025-02-12 20:56 UTC, tillprochaska approved these changes

2025-02-12 23:19 UTC, merged

2025-02-13 07:27 UTC, molefrog commented
Available in the latest release!

2025-02-13 08:59 UTC, tillprochaska commented
Thank you both, much appreciated!